Repository mavlink/mavros, pull requests merged in 2018-11, with the labels that each got.

#1103 Fix of trigger setup and control via mavlink cmd interface
  mavros/src/mavros/command.py
  mavros/src/plugins/command.cpp
  mavros_msgs/CMakeLists.txt
  mavros_msgs/srv/CommandTriggerControl.srv
  mavros_msgs/srv/CommandTriggerInterval.srv
Labels: enhancement

#1111 with this fix ,it will avoid eigen error on 32 bits system
  mavros/src/plugins/hil.cpp
Labels: enhancement, fix, plugin

#1112 fix: a typing error "alredy" to "already"
  mavros/src/plugins/command.cpp
Labels: fix

#1119 libmavconn: add the possibility to override the source component ID
  libmavconn/include/mavconn/interface.h
  libmavconn/include/mavconn/msgbuffer.h
  libmavconn/include/mavconn/serial.h
  libmavconn/include/mavconn/tcp.h
  libmavconn/include/mavconn/udp.h
  libmavconn/src/interface.cpp
  libmavconn/src/serial.cpp
  libmavconn/src/tcp.cpp
  libmavconn/src/udp.cpp
Labels: Protocol, messages

#1127 Fix mavros/param.py to work in python2 and python3, #940
  mavros/src/mavros/param.py
Labels: enhancement
