Repository mavlink/mavros, pull requests merged in 2019-10, with the labels that each got.

#1325 Travis CI: remove Lunar since it's EOL
  .travis.yml
Labels: fix, tests

#1287 libmavconn: simplify parse_buffer, and fix dropped_packets and parse_error counters
  libmavconn/include/mavconn/interface.h
  libmavconn/src/interface.cpp
Labels: bug, fix

#1297 adding mount orientation to mount_control plugin
  mavros_extras/src/plugins/mount_control.cpp
Labels: enhancement, extras
