Repository mavlink/mavros, pull requests merged in 2021-12, with the labels that each got.

#1667 fix bof
  mavros_extras/src/plugins/trajectory.cpp
Labels: bug, fix

#1670 Fix spurious bug because class field was uninitialized.
  mavros/src/lib/mavros_uas.cpp
Labels: ros2, fix

#1672 Set time/publish_sim_time to false by default
  mavros/src/plugins/sys_time.cpp
Labels: plugin, fix

#1675 fix bof
  mavros_extras/src/plugins/mag_calibration_status.cpp
Labels: plugin, ros2, fix

#1679 libmavconn: fix deadlock when call close()
  libmavconn/src/tcp.cpp
Labels: bug, fix

#1677 Add plugin for reporting terrain height estimate from the FCU
  mavros_extras/CMakeLists.txt
  mavros_extras/mavros_plugins.xml
  mavros_extras/src/plugins/terrain.cpp
  mavros_msgs/CMakeLists.txt
  mavros_msgs/msg/TerrainReport.msg
Labels: APM, plugin, extras

#1680 Add extra MAV_FRAMES to waypoint message
  mavros_msgs/msg/Waypoint.msg
Labels: API change, messages

#1682 fix std::system_error when tcp interface loses connection
  libmavconn/include/mavconn/tcp.hpp
  libmavconn/src/tcp.cpp
Labels: fix
