Repository mavlink/mavros, pull requests merged in 2022-05, with the labels that each got.

#1742 ESCTelemetryItem.msg: correct RPM units
  mavros_msgs/msg/ESCTelemetryItem.msg
Labels: documentation

#1745 fix subscribe_raw_salellites typo
  mavros/mavros/global_position.py
Labels: ros2, fix

#1744 mount_control.cpp: detect MOUNT_ORIENTATION stale messages
  mavros/launch/apm_config.yaml
  mavros/launch/px4_config.yaml
  mavros_extras/src/plugins/mount_control.cpp
Labels: enhancement, extras
