Repository mavlink/mavros, pull requests merged in 2023-02, with the labels that each got.

#1829 Made it such that the gp_origin topic publisher is latched.
  mavros/src/plugins/global_position.cpp
Labels: enhancement, plugin

#1833 plugins: ftp: fix null pointer dereference
  mavros/src/plugins/ftp.cpp
Labels: bug

#1834 fix px4 launch file for ROS2
  mavros/launch/apm.launch
  mavros/launch/apm2.launch
  mavros/launch/apm_config.yaml
  mavros/launch/apm_pluginlists.yaml
  mavros/launch/event_launcher.yaml
  mavros/launch/mavlink_bridge.launch
  mavros/launch/node.launch
  mavros/launch/px4.launch
  mavros/launch/px4_config.yaml
  mavros/launch/px4_pluginlists.yaml
Labels: enhancement, ros2
