Repository mavlink/mavros, pull requests merged in 2023-10, with the labels that each got.

#1904 Fix errata in GPSRAW.msg
  mavros_msgs/msg/GPSRAW.msg
Labels: messages, ros2, fix

#1908 GPS_STATUS: Fill in available messages for ROS1 legacy
  mavros_extras/src/plugins/gps_status.cpp
Labels: enhancement

#1862 Use SensorDataQoS for gp_origin subscriber
  mavros_extras/src/plugins/guided_target.cpp
Labels: ros2

#1910 Removed unused variable
  mavros_extras/src/plugins/guided_target.cpp
Labels: ros2

#1913 Fix typo
  mavros_extras/src/plugins/odom.cpp
Labels: ros2, fix
