Repository mavlink/mavros, pull requests merged in 2025-05, with the labels that each got.

#2037 Fix incorrect macro usage
  mavros/include/mavros/mavros_router.hpp
  mavros/include/mavros/plugin.hpp
Labels: build error, ros2, fix

#2039 Fix crash in gps_input plugin
  mavros_extras/src/plugins/gps_input.cpp
Labels: fix

#2042 fix: display topic on service timeout error
  mavros/mavros/base.py
Labels: bug, ros2, fix
